apiVersion: v1
kind: Pod
metadata:
  name: go-app-pod
spec:
  containers:
  - name: go-app
    image: jerry8287/docker-play:latest
    env:
      - name: "PORT"
        value: "8000"
      - name: "DRIVER"
        value: "mysql"
      - name: "ADDRESS"
        value: "10.154.156.136"
      - name: "DB_PORT"
        value: "3306"
      - name: "USERNAME"
        value: "root"
      - name: "PASSWORD"
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: password
      - name: "NAME"
        value: "alta"
    ports:
    - containerPort: 8000

